import { Roboto } from "next/font/google";
import "./globals.css";
import { UIContextProvider } from "@/contexts/UIContext";
import { TasksListContextProvider } from "@/contexts/taskListContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
  style: "normal",
  variable: "--font-roboto",
});

export const metadata = {
  title: "Mahmoud Bakr to do app",
  description: "Generated by Mahmoud Bakr",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={`antialiased min-h-screen`}>
        <TasksListContextProvider>
          <UIContextProvider>{children}</UIContextProvider>
        </TasksListContextProvider>
      </body>
    </html>
  );
}
